src/Entity/Creneaux.php
<?php

namespace App\Entity;

use App\Repository\CreneauxRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CreneauxRepository::class)]
class Creneaux
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: "datetime")]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column]
    private ?bool $isAvailable = true;

    #[ORM\ManyToOne(inversedBy: 'creneauxes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'creneauxes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Permis $permis = null;

    #[ORM\ManyToOne(inversedBy: 'creneauxess')]
    private ?User $user_Eleve = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): static
    {
        $this->date = $date;

        return $this;
    }

    public function isIsAvailable(): ?bool
    {
        return $this->isAvailable;
    }

    public function setIsAvailable(bool $isAvailable): static
    {
        $this->isAvailable = $isAvailable;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getPermis(): ?Permis
    {
        return $this->permis;
    }

    public function setPermis(?Permis $permis): static
    {
        $this->permis = $permis;

        return $this;
    }

    public function getUserEleve(): ?User
    {
        return $this->user_Eleve;
    }

    public function setUserEleve(?User $user_Eleve): static
    {
        $this->user_Eleve = $user_Eleve;

        return $this;
    }

    
}

src/Form/CreneauxType.php
<?php
// src/Form/CreneauxType.php

// src/Form/CreneauxType.php

namespace App\Form;

use App\Entity\Creneaux;
use App\Entity\Permis;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CreneauxType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date', null, [
                'label' => 'Date:',
            
            ])
            ->add('permis', EntityType::class, [
                'class' => Permis::class,
                'label' => 'Type:',
                'choice_label' => 'type',
               
            ])
        
            ->add('user', EntityType::class, [
                'class' => User::class,
                'label' => 'Moniteur:',
                'choice_label' => 'firstname',
                'choices' => $options["moniteur"],
                
               
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Creneaux::class,
            'moniteur' => null,
            'eleve' => null,
           
            
        ]);
    }
}

src/Controller/CreneauxController.php
<?php

namespace App\Controller;

use App\Service\Cart;
use App\Entity\Creneaux;
use App\Form\CreneauxType;
use App\Repository\UserRepository;
use App\Repository\CreneauxRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/creneaux')]
class CreneauxController extends AbstractController
{   

    #[Route('/', name: 'app_creneaux_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, UserRepository $userRepository): Response
    {

        $moniteur = $userRepository->getUsersByRole('ROLE_MONITEUR');
        $eleve = $userRepository->getUsersByRole('ROLE_ELEVE');
        // dd($moniteur);
        $creneaux = new Creneaux();
        $form = $this->createForm(CreneauxType::class, $creneaux, ["moniteur" => $moniteur, "eleve"=>$eleve]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($creneaux);
            $entityManager->flush();

            return $this->redirectToRoute('app_creneaux_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('creneaux/new.html.twig', [
            'creneaux' => $creneaux,
            'form' => $form,
        ]);
    }

    #[Route('/list', name: 'app_creneaux_index', methods: ['GET'])]
    public function index(CreneauxRepository $creneauxRepository): Response
    {
        // $creneauxes = $creneauxRepository->findAll();
        return $this->render('creneaux/list.html.twig', [
            'creneauxes' => $creneauxRepository->findAll(),
        ]);
    }

    #[Route('/{id}', name: 'app_creneaux_show', methods: ['GET'])]
    public function show(Creneaux $creneaux): Response
    { 
        return $this->render('creneaux/show.html.twig', [
            'creneaux' => $creneaux,
        ]);
    }
    

    #[Route('/{id}/edit', name: 'app_creneaux_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Creneaux $creneaux, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CreneauxType::class, $creneaux);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_creneaux_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('creneaux/edit.html.twig', [
            'creneaux' => $creneaux,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_creneaux_delete', methods: ['POST'])]
    public function delete(Request $request, Creneaux $creneaux, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$creneaux->getId(), $request->request->get('_token'))) {
            $entityManager->remove($creneaux);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_creneaux_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/{id}/update', name: 'app_creneaux_update', methods: ['GET', 'POST'])]
    public function update(Request $request, Creneaux $creneaux, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CreneauxType::class, $creneaux);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();
    
            // Ajoutez une instruction dump pour déboguer
            dump('Redirection effectuée');
    
            return $this->redirectToRoute('app_creneaux_index', [], Response::HTTP_SEE_OTHER);
        }
    
        return $this->render('creneaux/updateCreneaux.html.twig', [
            'creneaux' => $creneaux,
            'form' => $form,
        ]);
    }

    #[Route('/creneaux/{id}/reserve', name: 'app_reserve_creneaux', methods: ['GET'])]
    public function reserveCreneaux(Creneaux $creneaux, EntityManagerInterface $entityManager): Response
    {
        // Vérifiez si la plage horaire est disponible
        if ($creneaux->isIsAvailable()) {
            // Mettez à jour la plage horaire comme réservée
            $creneaux->setIsAvailable(false);
    
            // Définissez l'élève qui a réservé la plage horaire 
            $user = $this->getUser(); // Supposons que vous avez implémenté l'authentification de l'utilisateur
            $creneaux->setUserEleve($user);
    
            $entityManager->flush();
    
            // Redirigez vers la page de la liste ou toute autre page appropriée
            return $this->redirectToRoute('app_creneaux_index');
        }
    
        // Gérez le cas où la plage horaire est déjà réservée
        // Vous voudrez peut-être personnaliser cette partie en fonction de vos besoins
        $this->addFlash('error', 'Cette plage horaire est déjà réservée.');
    
        // Redirigez vers la page de la liste ou toute autre page appropriée
        return $this->redirectToRoute('app_creneaux_index');
    }

    #[Route('/creneaux/validate', name: 'app_creneaux_validate', methods: ['GET'])]
    public function validateCreneaux(EntityManagerInterface $entityManager, Cart $cart): Response
    {
        $cartCreneaux = $cart->getDetails();
        $creneaux = $cartCreneaux['creneaux'];
        
        foreach($creneaux as $infoCreneau){
            $creneau = $infoCreneau['creneau'];
            // Vérifiez si la plage horaire est disponible
            if ($creneau->isIsAvailable()) {
                // Mettez à jour la plage horaire comme réservée
                $creneau->setIsAvailable(false);
        
                // Définissez l'élève qui a réservé la plage horaire 
                $user = $this->getUser(); // Supposons que vous avez implémenté l'authentification de l'utilisateur
                $creneau->setUserEleve($user);
                $entityManager->persist($creneau);        
            }     
        }

        $entityManager->flush();
        $cart->remove();
        $this->addFlash('success', 'Vos créneaux sont validés.'); 
         
        // Redirigez vers la page de la liste ou toute autre page appropriée
        return $this->redirectToRoute('app_creneaux_index'); 
    }

    #[Route('/creneaux/{id}/cancel', name: 'app_cancel', methods: ['GET'])]
    public function cancel(Creneaux $creneaux, EntityManagerInterface $entityManager): Response
    {
        // Vérifiez si l'utilisateur connecté a réservé cette plage horaire
        $user = $this->getUser();
        if ($user && $creneaux->getUserEleve() === $user) {
            // Annulez la réservation en mettant à jour la plage horaire comme disponible
            $creneaux->setIsAvailable(true);
            $creneaux->setUserEleve(null); // Définissez l'élève comme null
    
            $entityManager->flush();
    
            // Redirigez vers la page de la liste ou toute autre page appropriée
            return $this->redirectToRoute('app_creneaux_index');
        }
    
        // Gérez le cas où l'utilisateur n'est pas autorisé à annuler cette réservation
        // Vous pouvez personnaliser cette partie en fonction de vos besoins
        $this->addFlash('error', 'Vous n\'êtes pas autorisé à annuler cette réservation.');
    
        // Redirigez vers la page de la liste ou toute autre page appropriée
        return $this->redirectToRoute('app_creneaux_index');
    }
}




   

templates/creneaux/_delete_form.html.twig
<form method="post" action="{{ path('app_creneaux_delete', {'id': creneaux.id}) }}" onsubmit="return confirm('Are you sure you want to delete this creneau?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ creneaux.id) }}">
    <button class="btn">Delete</button>
</form>

templates/creneaux/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}  
    <button class="btnFormCreneaux">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/creneaux/edit.html.twig
{# templates/creneaux/edit.html.twig #}
{% extends 'base.html.twig' %}

{% block title %}Edit Creneaux{% endblock %}

{% block body %}
{% if 'ROLE_ADMIN' not in app.user.roles %}
        <div class="alert alert-danger" role="alert">
            Vous n'avez pas les droits d'accéder à cette page.
        </div>
{% else %}
    <div class="editGenerale">
        <h4>Edit Creneau</h4>
      
        {{ form_start(form) }}
        {{ form_widget(form) }}

        <button type="submit" class="btnUpdate">Update</button>
        {{ form_end(form) }}

        {# <div class="deleteFormContainer">
            {{ include('creneaux/_delete_form.html.twig') }}
        </div> #}

        <a class="btnEdit" href="{{ path('app_creneaux_index') }}"><span>&#128412;</span>List</a>
    </div>
{% endif %}

{% endblock %}

templates/creneaux/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Creneaux index{% endblock %}

{% block body %}
    <div class="creneauxGeneral">
        <h2>Creneaux List</h2>

        <table class="crenauxtable">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Is Available</th>
                    <th>Moniteurs</th>
                    {% if is_granted('ROLE_ELEVE') %}
                        <th>ELEVE</th>
                    {% else %}
                        <th>Elèves</th>
                    {% endif %}
                    <th>Permis Type</th>
                    <th>Price:€</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for creneau in creneauxes %}
                    {% if creneau.isAvailable or creneau.userEleve.id is defined and creneau.userEleve.id == app.user.id or is_granted('ROLE_ADMIN') or is_granted('ROLE_MONITEUR') %}
                        <tr>
                            <td>{{ creneau.date ? creneau.date|date('Y-m-d H:i:s') : '' }}</td>
                            <td>{{ creneau.isAvailable ? 'Yes' : 'No' }}</td>
                            <td>{{ creneau.user is not null ? creneau.user.firstname : '' }}</td>
                            
                            {% if is_granted('ROLE_ELEVE') %}
                                {% if creneau.userEleve.id is defined and creneau.userEleve.id == app.user.id %}
                                    <td>{{ app.user.firstname }}</td>
                                {% else %}
                                    <td></td>
                                {% endif %}
                            {% elseif is_granted('ROLE_ADMIN') or is_granted('ROLE_MONITEUR') %}
                                <td>{{ creneau.userEleve.id is defined ? creneau.userEleve.firstname : '' }}</td>
                            {% else %}
                                <td></td>
                            {% endif %}

                            <td>{{ creneau.permis.type }}</td>
                            <td>{{ creneau.permis.price }}</td>
                            <td>
                                {% if 'ROLE_ADMIN' in app.user.roles %}
                                    <a href="{{ path('app_creneaux_edit', {'id': creneau.id}) }}">Modifier</a>
                                    <a href="{{ path('app_creneaux_show', {'id': creneau.id}) }}">Afficher</a>
                                {# {% elseif 'ROLE_MONITEUR' in app.user.roles %} #}
                                {% elseif 'ROLE_ELEVE' in app.user.roles %}
                                    {% if creneau.isAvailable %}
                                        <a href="{{ path('add_to_cart', {'id': creneau.id}) }}">Réserver</a>
                                    {% else %}
                                        {# <a href="{{ path('app_cancel', {'id': creneau.id}) }}">Annuler</a> #}
                                        Réservé
                                    {% endif %}
                                {% endif %}
                            </td>
                        </tr>
                    {% endif %}
                {% else %}
                    <tr>
                        <td colspan="7">No records found</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="crenauxA">          
            {% if 'ROLE_ADMIN' in app.user.roles %}
            <a href="{{ path('app_creneaux_new') }}">Create new</a>
                                    
            {% elseif 'ROLE_ELEVE' in app.user.roles %}
             <a href="{{ path('cart') }}">Voir Mon Panier</a>
            {% endif %}
             
        </div>
    </div>
{% endblock %}

templates/creneaux/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Creneaux{% endblock %}

{% block body %}
{% if 'ROLE_ADMIN' not in app.user.roles %}
        <div class="alert alert-danger" role="alert">
            Vous n'avez pas les droits d'accéder à cette page.
        </div>
{% else %}
 <div class="newGenerale">
    <h4>Creneaux Form</h4>
    {# <a href="{{ path('app_creneaux_index') }}"><span>&#128412;</span>List</a> #}

    {{ include('creneaux/_form.html.twig') }}

    <a href="{{ path('app_creneaux_index') }}"><span>&#128412;</span>List</a>
 </div>
{% endif %}

{% endblock %}

templates/creneaux/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Créneaux{% endblock %}

{% block body %}
{% if 'ROLE_ADMIN' not in app.user.roles %}
        <div class="alert alert-danger" role="alert">
            Vous n'avez pas les droits d'accéder à cette page.
        </div>
{% else %}
   <div class="showCreneaux" >
        <h4 >Détail Creneau</h4>
        <table >
            <tbody>
                <tr>
                    <th>Id</th>
                    <td>{{ creneaux.id }}</td>
                </tr>
                <tr>
                    <th>Date</th>
                    <td>{{ creneaux.date ? creneaux.date|date('Y-m-d H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>Moniteur</th>
                    <td>{{ creneaux.user.firstname }}</td>
                </tr>
           
                <tr>
                    <th>Permis Type</th>
                    <td>{{ creneaux.permis.type }}</td>
                </tr>
                <tr>
                    <th>IsAvailable</th>
                    <td>{{ creneaux.isAvailable ? 'Yes' : 'No' }}</td>
                </tr>
            </tbody>
        </table> 
         <div class="btnShow">
            <a href="{{ path('app_creneaux_index') }}"><span>&#128412;</span>List</a>
            <a href="{{ path('app_creneaux_edit', {'id': creneaux.id}) }}">Edit</a>
        </div>
        {{ include('creneaux/_delete_form.html.twig') }}
  </div>
{% endblock %}
{% endblock %}

templates/creneaux/updateCreneaux.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Creneaux{% endblock %}

{% block body %}
    <div class="editGenerale">
        <h4>Modifier Creneaux</h4>

        {{ form_start(form, {'method': 'POST'}) }}

        <button type="submit" class="btnUpdate">Update</button>

        {{ form_end(form) }}

        <div class="deleteFormContainer">
            {{ include('creneaux/_delete_form.html.twig') }}
        </div>

        <a class="btnEdit" href="{{ path('app_creneaux_index') }}"><span>&#128412;</span>List</a>
    </div>
{% endblock %}